"""Permission handling for tool execution."""

from ripperdoc.cli.ui.choice import prompt_choice

from .constants import (
    AUTO_MEMORY_WRITE_TOOLS,
    EDIT_PREVIEW_MATCH_SNIPPET_MAX,
    EDIT_PREVIEW_MAX_BYTES,
    EDIT_PREVIEW_MAX_DIFF_LINES,
    EDIT_PREVIEW_SEPARATOR,
    PERMISSION_MODES,
    PERMISSION_PROMPT_MIN_DIFF_LINES,
    PERMISSION_PROMPT_RESERVED_LINES,
    PLAN_MODE_PLAN_FILE_EDIT_TOOLS,
    PLAN_MODE_SPECIAL_ALLOWED_TOOLS,
    _AUTO_MEMORY_WRITE_TOOLS,
    _EDIT_PREVIEW_MATCH_SNIPPET_MAX,
    _EDIT_PREVIEW_MAX_BYTES,
    _EDIT_PREVIEW_MAX_DIFF_LINES,
    _EDIT_PREVIEW_SEPARATOR,
    _PERMISSION_MODES,
    _PERMISSION_PROMPT_MIN_DIFF_LINES,
    _PERMISSION_PROMPT_RESERVED_LINES,
    _PLAN_MODE_PLAN_FILE_EDIT_TOOLS,
    _PLAN_MODE_SPECIAL_ALLOWED_TOOLS,
    _TOOL_RULE_HINT_RE,
)
from .decision import (
    _coerce_permission_decision,
    _default_permission_decision,
    _dont_ask_permission_denied_message,
    _extract_input_file_path,
    _extract_tool_target_path,
    _is_rule_ask_decision,
    _normalize_permission_mode,
    _permission_denied_message,
    _permission_request_allow_can_override,
    _plan_mode_restriction_result,
    _resolve_auto_memory_write_decision,
    _resolve_permission_decision,
    _run_permission_decision_engine,
)
from .keys import _rule_strings, _serialize_permission_suggestions, permission_key
from .models import PermissionPreview, PermissionResult
from .policy import (
    _apply_updated_permissions,
    _as_str_set,
    _build_permission_policy,
    _explicit_rule_decision,
    _extract_tool_specifier_rules,
    _managed_permissions_only_enabled,
    _parse_rule_collection,
    _resolve_explicit_rule_decision,
    _session_rule_to_raw,
)
from .preview import (
    _build_edit_permission_preview,
    _build_write_permission_preview,
    _compact_preview_snippet,
    _compute_edit_preview,
    _format_input_preview,
    _normalize_edit_operations,
    _permission_preview_diff_line_budget,
)
from .runtime import make_permission_checker

__all__ = [
    "PermissionResult",
    "PermissionPreview",
    "permission_key",
    "make_permission_checker",
    "prompt_choice",
    "EDIT_PREVIEW_MAX_DIFF_LINES",
    "EDIT_PREVIEW_MAX_BYTES",
    "EDIT_PREVIEW_MATCH_SNIPPET_MAX",
    "EDIT_PREVIEW_SEPARATOR",
    "PERMISSION_PROMPT_RESERVED_LINES",
    "PERMISSION_PROMPT_MIN_DIFF_LINES",
    "PERMISSION_MODES",
    "AUTO_MEMORY_WRITE_TOOLS",
    "PLAN_MODE_SPECIAL_ALLOWED_TOOLS",
    "PLAN_MODE_PLAN_FILE_EDIT_TOOLS",
    "_TOOL_RULE_HINT_RE",
    "_EDIT_PREVIEW_MAX_DIFF_LINES",
    "_EDIT_PREVIEW_MAX_BYTES",
    "_EDIT_PREVIEW_MATCH_SNIPPET_MAX",
    "_EDIT_PREVIEW_SEPARATOR",
    "_PERMISSION_PROMPT_RESERVED_LINES",
    "_PERMISSION_PROMPT_MIN_DIFF_LINES",
    "_PERMISSION_MODES",
    "_AUTO_MEMORY_WRITE_TOOLS",
    "_PLAN_MODE_SPECIAL_ALLOWED_TOOLS",
    "_PLAN_MODE_PLAN_FILE_EDIT_TOOLS",
    "_format_input_preview",
    "_build_edit_permission_preview",
    "_build_write_permission_preview",
    "_permission_preview_diff_line_budget",
    "_compact_preview_snippet",
    "_compute_edit_preview",
    "_normalize_edit_operations",
    "_rule_strings",
    "_serialize_permission_suggestions",
    "_as_str_set",
    "_managed_permissions_only_enabled",
    "_apply_updated_permissions",
    "_parse_rule_collection",
    "_extract_tool_specifier_rules",
    "_session_rule_to_raw",
    "_explicit_rule_decision",
    "_resolve_explicit_rule_decision",
    "_build_permission_policy",
    "_extract_input_file_path",
    "_resolve_auto_memory_write_decision",
    "_default_permission_decision",
    "_permission_denied_message",
    "_dont_ask_permission_denied_message",
    "_normalize_permission_mode",
    "_is_rule_ask_decision",
    "_extract_tool_target_path",
    "_permission_request_allow_can_override",
    "_plan_mode_restriction_result",
    "_coerce_permission_decision",
    "_resolve_permission_decision",
    "_run_permission_decision_engine",
]
