"""Permission engine constants and compatibility aliases."""

from __future__ import annotations

import re

from ripperdoc.constants.permissions import (
    EDIT_PREVIEW_MAX_DIFF_LINES,
    EDIT_PREVIEW_MAX_BYTES,
    EDIT_PREVIEW_MATCH_SNIPPET_MAX,
    EDIT_PREVIEW_SEPARATOR,
    PERMISSION_PROMPT_RESERVED_LINES,
    PERMISSION_PROMPT_MIN_DIFF_LINES,
    PERMISSION_MODES,
    AUTO_MEMORY_WRITE_TOOLS,
    PLAN_MODE_SPECIAL_ALLOWED_TOOLS,
    PLAN_MODE_PLAN_FILE_EDIT_TOOLS,
)


# Backward-compatible aliases (prefixed with underscore)
_TOOL_RULE_HINT_RE = re.compile(r"^[A-Za-z0-9_-]+\s*\(.*\)\s*$")
_EDIT_PREVIEW_MAX_DIFF_LINES = EDIT_PREVIEW_MAX_DIFF_LINES
_EDIT_PREVIEW_MAX_BYTES = EDIT_PREVIEW_MAX_BYTES
_EDIT_PREVIEW_MATCH_SNIPPET_MAX = EDIT_PREVIEW_MATCH_SNIPPET_MAX
_EDIT_PREVIEW_SEPARATOR = EDIT_PREVIEW_SEPARATOR
_PERMISSION_PROMPT_RESERVED_LINES = PERMISSION_PROMPT_RESERVED_LINES
_PERMISSION_PROMPT_MIN_DIFF_LINES = PERMISSION_PROMPT_MIN_DIFF_LINES
_PERMISSION_MODES = PERMISSION_MODES
_AUTO_MEMORY_WRITE_TOOLS = AUTO_MEMORY_WRITE_TOOLS
_PLAN_MODE_SPECIAL_ALLOWED_TOOLS = PLAN_MODE_SPECIAL_ALLOWED_TOOLS
_PLAN_MODE_PLAN_FILE_EDIT_TOOLS = PLAN_MODE_PLAN_FILE_EDIT_TOOLS
