"""Environment variable name constants for RIPPERDOC_* overrides."""

RIPPERDOC_BASE_URL = "RIPPERDOC_BASE_URL"
RIPPERDOC_AUTH_TOKEN = "RIPPERDOC_AUTH_TOKEN"
RIPPERDOC_MODEL = "RIPPERDOC_MODEL"
RIPPERDOC_SMALL_FAST_MODEL = "RIPPERDOC_SMALL_FAST_MODEL"
RIPPERDOC_API_KEY = "RIPPERDOC_API_KEY"
RIPPERDOC_PROTOCOL = "RIPPERDOC_PROTOCOL"
