"""Messaging type definitions — re-exports from submodules."""

from .content import MessageContent
from .attachment import (
    AttachmentPayload,
    UnknownAttachmentPayload,
    HookAdditionalContextAttachmentPayload,
    PlanModeAttachmentPayload,
    DirectoryAttachmentPayload,
    EditedTextFileAttachmentPayload,
    FileAttachmentContent,
    UnknownFileAttachmentContent,
    FileTextAttachmentContent,
    FileImageAttachmentContent,
    FileNotebookAttachmentContent,
    FilePdfAttachmentContent,
    FileAttachmentContentModel,
    FileAttachmentPayload,
    CompactFileReferenceAttachmentPayload,
    PdfReferenceAttachmentPayload,
    SelectedLinesInIdeAttachmentPayload,
    OpenedFileInIdeAttachmentPayload,
    TodoAttachmentPayload,
    PlanFileReferenceAttachmentPayload,
    InvokedSkillsAttachmentPayload,
    TodoReminderAttachmentPayload,
    TaskReminderAttachmentPayload,
    NestedMemoryAttachmentPayload,
    RelevantMemoriesAttachmentPayload,
    SkillListingAttachmentPayload,
    QueuedCommandAttachmentPayload,
    UltramemoryAttachmentPayload,
    McpResourceAttachmentPayload,
    AgentMentionAttachmentPayload,
    OutputStyleAttachmentPayload,
    TaskStatusAttachmentPayload,
    TaskProgressAttachmentPayload,
    DiagnosticsAttachmentPayload,
    CriticalSystemReminderAttachmentPayload,
    DateChangeAttachmentPayload,
    TokenUsageAttachmentPayload,
    BudgetUsdAttachmentPayload,
    AsyncHookResponseAttachmentPayload,
    HookBlockingErrorAttachmentPayload,
    HookSuccessAttachmentPayload,
    HookStoppedContinuationAttachmentPayload,
    CompactionReminderAttachmentPayload,
    VerifyPlanReminderAttachmentPayload,
    DynamicSkillAttachmentPayload,
    AlreadyReadFileAttachmentPayload,
    CommandPermissionsAttachmentPayload,
    EditedImageFileAttachmentPayload,
    HookCancelledAttachmentPayload,
    HookErrorDuringExecutionAttachmentPayload,
    HookNonBlockingErrorAttachmentPayload,
    HookSystemMessageAttachmentPayload,
    StructuredOutputAttachmentPayload,
    HookPermissionDecisionAttachmentPayload,
    AutocheckpointingAttachmentPayload,
    BackgroundTaskStatusAttachmentPayload,
    AttachmentPayloadModel,
    ATTACHMENT_PAYLOAD_MODEL_BY_TYPE,
    _coerce_attachment_payload,
    _coerce_file_attachment_content,
    ATTACHMENT_IGNORED_TYPES,
    ATTACHMENT_EXPORT_HIDDEN_TYPES,
    ATTACHMENT_SUMMARY_HIDDEN_TYPES,
)
from .message import (
    MessageRole,
    Message,
    UserMessage,
    AssistantMessage,
    ProgressMessage,
    AttachmentMessage,
)

# Unified conversation message type alias
from typing import Union as _Union

ConversationMessage = _Union[UserMessage, AssistantMessage, ProgressMessage, AttachmentMessage]

__all__ = [
    # content
    "MessageContent",
    # attachment payloads
    "AttachmentPayload",
    "UnknownAttachmentPayload",
    "HookAdditionalContextAttachmentPayload",
    "PlanModeAttachmentPayload",
    "DirectoryAttachmentPayload",
    "EditedTextFileAttachmentPayload",
    "FileAttachmentContent",
    "UnknownFileAttachmentContent",
    "FileTextAttachmentContent",
    "FileImageAttachmentContent",
    "FileNotebookAttachmentContent",
    "FilePdfAttachmentContent",
    "FileAttachmentContentModel",
    "FileAttachmentPayload",
    "CompactFileReferenceAttachmentPayload",
    "PdfReferenceAttachmentPayload",
    "SelectedLinesInIdeAttachmentPayload",
    "OpenedFileInIdeAttachmentPayload",
    "TodoAttachmentPayload",
    "PlanFileReferenceAttachmentPayload",
    "InvokedSkillsAttachmentPayload",
    "TodoReminderAttachmentPayload",
    "TaskReminderAttachmentPayload",
    "NestedMemoryAttachmentPayload",
    "RelevantMemoriesAttachmentPayload",
    "SkillListingAttachmentPayload",
    "QueuedCommandAttachmentPayload",
    "UltramemoryAttachmentPayload",
    "McpResourceAttachmentPayload",
    "AgentMentionAttachmentPayload",
    "OutputStyleAttachmentPayload",
    "TaskStatusAttachmentPayload",
    "TaskProgressAttachmentPayload",
    "DiagnosticsAttachmentPayload",
    "CriticalSystemReminderAttachmentPayload",
    "DateChangeAttachmentPayload",
    "TokenUsageAttachmentPayload",
    "BudgetUsdAttachmentPayload",
    "AsyncHookResponseAttachmentPayload",
    "HookBlockingErrorAttachmentPayload",
    "HookSuccessAttachmentPayload",
    "HookStoppedContinuationAttachmentPayload",
    "CompactionReminderAttachmentPayload",
    "VerifyPlanReminderAttachmentPayload",
    "DynamicSkillAttachmentPayload",
    "AlreadyReadFileAttachmentPayload",
    "CommandPermissionsAttachmentPayload",
    "EditedImageFileAttachmentPayload",
    "HookCancelledAttachmentPayload",
    "HookErrorDuringExecutionAttachmentPayload",
    "HookNonBlockingErrorAttachmentPayload",
    "HookSystemMessageAttachmentPayload",
    "StructuredOutputAttachmentPayload",
    "HookPermissionDecisionAttachmentPayload",
    "AutocheckpointingAttachmentPayload",
    "BackgroundTaskStatusAttachmentPayload",
    "AttachmentPayloadModel",
    "ATTACHMENT_PAYLOAD_MODEL_BY_TYPE",
    "_coerce_attachment_payload",
    "_coerce_file_attachment_content",
    "ATTACHMENT_IGNORED_TYPES",
    "ATTACHMENT_EXPORT_HIDDEN_TYPES",
    "ATTACHMENT_SUMMARY_HIDDEN_TYPES",
    # messages
    "MessageRole",
    "Message",
    "UserMessage",
    "AssistantMessage",
    "ProgressMessage",
    "AttachmentMessage",
    "ConversationMessage",
]
