"""Compatibility facade for protocol DTOs.

Focused protocol model definitions live in ``ripperdoc.protocol.model_types``.
"""

from __future__ import annotations

from ripperdoc.protocol.model_types.content import (
    ContentBlock,
    ContentBlockType,
    ImageContentBlock,
    ImageSource,
    TextContentBlock,
    ThinkingContentBlock,
    ToolResultContentBlock,
    ToolUseContentBlock,
)
from ripperdoc.protocol.model_types.context import (
    ContextCategory,
    ContextGridSquare,
    ContextUsageResult,
)
from ripperdoc.protocol.model_types.helpers import model_to_dict
from ripperdoc.protocol.model_types.initialize import (
    InitializeClientCapabilities,
    InitializeClientIcon,
    InitializeClientInfo,
    InitializeParams,
    InitializeResult,
    InitializeServerInfo,
    ProtocolCapabilities,
)
from ripperdoc.protocol.model_types.jsonrpc import (
    DEFAULT_PROTOCOL_VERSION,
    JsonRpcError,
    JsonRpcErrorCodes,
    JsonRpcResponse,
    JsonRpcResponseError,
)
from ripperdoc.protocol.model_types.mcp import (
    MCPServerInfo,
    MCPServerStatusInfo,
    McpServerCapabilities,
    McpServerStatusDetail,
    McpToolAnnotation,
    McpToolInfo,
)
from ripperdoc.protocol.model_types.permissions import (
    PermissionDecisionClassification,
    PermissionRequestPayload,
    PermissionResponseAllow,
    PermissionResponseDeny,
    PermissionRuleValue,
    PermissionUpdate,
    PermissionUpdateAddDirectories,
    PermissionUpdateAddRules,
    PermissionUpdateDestination,
    PermissionUpdateRemoveDirectories,
    PermissionUpdateRemoveRules,
    PermissionUpdateReplaceRules,
    PermissionUpdateSetMode,
    ToolCallRequest,
)
from ripperdoc.protocol.model_types.sampling import (
    SamplingRequest,
    SamplingRequestMessage,
    SamplingResult,
    UsageInfo,
)
from ripperdoc.protocol.model_types.sdk import (
    AccountInfo,
    FastModeState,
    ModelInfo,
    SDKAuthStatusMessage,
    SDKPromptSuggestionMessage,
    SDKResultMessage,
    SDKStatusMessage,
    SDKToolProgressMessage,
    SdkBeta,
    SlashCommandInfo,
    ThinkingConfig,
)
from ripperdoc.protocol.model_types.stream import (
    AssistantMessageData,
    AssistantStreamMessage,
    IncomingUserMessageData,
    IncomingUserStreamMessage,
    MessageData,
    StreamMessage,
    UserMessageData,
    UserStreamMessage,
)

__all__ = [
    "DEFAULT_PROTOCOL_VERSION",
    "JsonRpcErrorCodes",
    "JsonRpcError",
    "JsonRpcResponse",
    "JsonRpcResponseError",
    "ContentBlock",
    "TextContentBlock",
    "ThinkingContentBlock",
    "ToolUseContentBlock",
    "ToolResultContentBlock",
    "ImageSource",
    "ImageContentBlock",
    "ContentBlockType",
    "MessageData",
    "AssistantMessageData",
    "UserMessageData",
    "AssistantStreamMessage",
    "UserStreamMessage",
    "StreamMessage",
    "IncomingUserMessageData",
    "IncomingUserStreamMessage",
    "MCPServerInfo",
    "MCPServerStatusInfo",
    "McpToolAnnotation",
    "McpToolInfo",
    "McpServerCapabilities",
    "McpServerStatusDetail",
    "ProtocolCapabilities",
    "InitializeClientIcon",
    "InitializeClientInfo",
    "InitializeClientCapabilities",
    "InitializeServerInfo",
    "InitializeResult",
    "InitializeParams",
    "SamplingRequestMessage",
    "SamplingRequest",
    "SamplingResult",
    "UsageInfo",
    "PermissionResponseAllow",
    "PermissionResponseDeny",
    "PermissionRequestPayload",
    "ToolCallRequest",
    "PermissionRuleValue",
    "PermissionUpdateDestination",
    "PermissionDecisionClassification",
    "PermissionUpdateAddRules",
    "PermissionUpdateReplaceRules",
    "PermissionUpdateRemoveRules",
    "PermissionUpdateSetMode",
    "PermissionUpdateAddDirectories",
    "PermissionUpdateRemoveDirectories",
    "PermissionUpdate",
    "FastModeState",
    "ThinkingConfig",
    "ModelInfo",
    "AccountInfo",
    "SlashCommandInfo",
    "SdkBeta",
    "ContextCategory",
    "ContextGridSquare",
    "ContextUsageResult",
    "SDKResultMessage",
    "SDKStatusMessage",
    "SDKToolProgressMessage",
    "SDKAuthStatusMessage",
    "SDKPromptSuggestionMessage",
    "model_to_dict",
]
