"""Shared constants for remote-control bridge components."""

from __future__ import annotations

import re

BASE_URL_ENV = "RIPPERDOC_REMOTE_CONTROL_BASE_URL"
INGRESS_URL_ENV = "RIPPERDOC_REMOTE_CONTROL_INGRESS_URL"
TOKEN_ENV = "RIPPERDOC_REMOTE_CONTROL_ACCESS_TOKEN"
ALLOW_HTTP_ENV = "RIPPERDOC_REMOTE_CONTROL_ALLOW_INSECURE_HTTP"
CONNECT_TEMPLATE_ENV = "RIPPERDOC_REMOTE_CONTROL_CONNECT_URL_TEMPLATE"
LEGACY_HEADERS_ENV = "RIPPERDOC_REMOTE_CONTROL_LEGACY_HEADERS"
POLL_ACK_IN_QUERY_ENV = "RIPPERDOC_REMOTE_CONTROL_POLL_ACK_IN_QUERY"

DEFAULT_SESSION_TIMEOUT_SEC = 86_400

CONNECTION_RETRY_INITIAL_SEC = 2.0
CONNECTION_RETRY_MAX_SEC = 120.0
CONNECTION_GIVEUP_SEC = 600.0

GENERAL_RETRY_INITIAL_SEC = 0.5
GENERAL_RETRY_MAX_SEC = 30.0
GENERAL_GIVEUP_SEC = 600.0

IDENTIFIER_RE = re.compile(r"^[a-zA-Z0-9_-]+$")
REMOTE_CONTROL_API_VERSION = "2023-06-01"
REMOTE_CONTROL_API_BETA = "environments-2025-11-01"
REMOTE_CONTROL_VERSION_HEADER = "x-ripperdoc-version"
REMOTE_CONTROL_BETA_HEADER = "x-ripperdoc-beta"

TOKEN_REFRESH_BUFFER_SEC = 300
TOKEN_REFRESH_FOLLOWUP_SEC = 1800
TOKEN_REFRESH_MAX_RETRIES = 3
TOKEN_REFRESH_RETRY_SEC = 60

SESSIONS_WS_RECONNECT_DELAY_SEC = 2.0
SESSIONS_WS_MAX_RECONNECTS = 5
SESSIONS_WS_PING_INTERVAL_SEC = 30.0
SESSIONS_WS_PERMANENT_CLOSE_CODES = {4001, 4003}
